events { worker_connections 1024; }

http {
    upstream tei_backend {
        # Round Robin (Default): Alternates requests 1 -> 2 -> 1 -> 2
        server tei-1:80;
        server tei-2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://tei_backend;
        }
    }
}